services:
  coindeskapi:
    image: coindeskapi
    build:
      context: .
      dockerfile: CoindeskApi/Dockerfile
    ports:
      - "12345:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=DockerDev